import { execFile } from 'child_process';
import { promisify } from 'util';
import * as os from 'os';
import * as path from 'path';
import * as fs from 'fs';
import { versionCmp } from './pure';
import type { DshDiagnostics } from './dsh-client';
import type { DshSettings } from './settings';

const execFileAsync = promisify(execFile);

/**
 * Command construction and environment probing for the dsh CLI.
 *
 * - Detects the `dsh` binary (explicit setting > PATH > common locations).
 * - Detects a Node.js binary and dsh's real entry script so the plugin can
 *   spawn `node <dsh>/lib/bin.js` directly. Obsidian's Electron process runs
 *   with a restricted PATH (no Homebrew/nvm dirs), so relying on the `dsh`
 *   shebang (`#!/usr/bin/env node`) fails with "env: node: No such file or
 *   directory".
 * - Warms up the `headless` profile on first use (dsh bootstraps the
 *   profile directory under DSH_HOME on demand).
 * - Generates the vault persona `--patch` overlay once per vault.
 * - Assembles the task text: conversation memory + user message.
 */

const COMMON_BIN_CANDIDATES = [
  '/opt/homebrew/bin/dsh',
  '/usr/local/bin/dsh',
  '/usr/bin/dsh',
];

const COMMON_NODE_CANDIDATES = [
  '/opt/homebrew/bin/node',
  '/usr/local/bin/node',
  '/usr/bin/node',
];

/**
 * Source of the stream-relay DSH plugin injected via --patch.
 * It listens on the live `session/event` stream and emits real-time
 * JSON Lines (`DLEVENT\t<json>`) for reasoning blocks and tool calls:
 *   {t:'think', text}                       reasoning increment
 *   {t:'tool', status:'start', id, name, args}   tool call started
 *   {t:'tool', status:'result', id, ok, summary} tool result
 * The headless runner itself only prints the final text at the end, so
 * without this plugin the plugin never sees thinking or tool activity live.
 */
const STREAM_RELAY_SRC = `// dsh-obsidian stream relay: real-time thinking + tool events.
// Injected as a patch overlay; owned and regenerated by the plugin.
module.exports = {
  name: 'dsh-obsidian-stream-relay',
  apply(ctx) {
    const callNames = new Map();
    const emit = (obj) => process.stdout.write('DLEVENT\\t' + JSON.stringify(obj) + '\\n');
    const truncate = (s, n) => (s.length > n ? s.slice(0, n) + '…' : s);
    const summarizeArgs = (args) => {
      if (!args || typeof args !== 'object') return String(args ?? '');
      const pick = ['command', 'filePath', 'path', 'query', 'pattern', 'url', 'text', 'target', 'from', 'to'];
      const parts = [];
      for (const k of pick) if (typeof args[k] === 'string' && args[k]) parts.push(k + '=' + truncate(args[k], 60));
      return parts.length ? parts.join(' ') : truncate(JSON.stringify(args), 120);
    };
    // Tool results nest text: [{type:'tool-result', content:[{type:'text', text}]}]
    const collectText = (node, out) => {
      if (Array.isArray(node)) {
        for (const c of node) collectText(c, out);
        return;
      }
      if (typeof node === 'string') { out.push(node); return; }
      if (!node || typeof node !== 'object') return;
      if (typeof node.text === 'string') out.push(node.text);
      if (Array.isArray(node.content)) {
        for (const c of node.content) collectText(c, out);
      } else if (node.content && typeof node.content === 'object') {
        collectText(node.content, out);
      }
    };
    const summarizeResult = (content) => {
      const out = [];
      collectText(content, out);
      const text = out.join('\\n').trim();
      return text ? truncate(text, 300) : '';
    };
    ctx.on('session/event', (session, event) => {
      switch (event.type) {
        case 'assistant/message': {
          for (const b of event.data.message.content ?? []) {
            if (b.type === 'reasoning' && b.text) emit({ t: 'think', text: b.text });
          }
          break;
        }
        case 'tool/call': {
          callNames.set(event.data.callId, event.data.name);
          emit({
            t: 'tool',
            status: 'start',
            id: event.data.callId,
            name: event.data.name,
            args: summarizeArgs(event.data.arguments),
            argsFull: JSON.stringify(event.data.arguments)
          });
          break;
        }
        case 'tool/result': {
          const msg = event.data.message ?? {};
          // callId lives on message.source.callId (not on the message root)
          const callId = msg.callId ?? msg.source?.callId;
          const name = callNames.get(callId) ?? 'tool';
          emit({ t: 'tool', status: 'result', id: callId, ok: msg.isError !== true, summary: summarizeResult(msg.content) });
          break;
        }
        default:
          break;
      }
    });
  }
};
`;

/** Whether a resolved dsh entry is a JS file node can run directly. */
function isNodeScript(p: string): boolean {
  if (/\.(?:m?js|cjs)$/i.test(p)) return true;
  try {
    return /^#!.*\bnode\b/.test(fs.readFileSync(p, 'utf8').slice(0, 128));
  } catch {
    return false;
  }
}

export class DshRunner {
  constructor(private settings: DshSettings) {}

  /** Resolve the dsh binary path, or null when not found. */
  async detectBin(): Promise<string | null> {
    const explicit = this.settings.dshBin.trim();
    if (explicit) {
      if (await this.exists(explicit)) return explicit;
      return null;
    }
    // PATH lookup
    try {
      const { stdout } = await execFileAsync('which', ['dsh'], { timeout: 5000 });
      const p = stdout.trim();
      if (p) return p;
    } catch {
      // not in PATH
    }
    for (const candidate of COMMON_BIN_CANDIDATES) {
      if (await this.exists(candidate)) return candidate;
    }
    return null;
  }

  /** Probe binary + profile readiness for the settings page. */
  async diagnose(): Promise<DshDiagnostics> {
    const bin = await this.detectBin();
    const nodeBin = await this.detectNode();
    if (!bin) {
      return { bin: '', found: false, version: null, error: 'not-found', nodeBin };
    }
    try {
      const script = this.resolveDshScript(bin);
      // Prefer `node <script> --version` (bypasses the shebang under Electron's
      // restricted PATH); when the bin isn't node-runnable, invoke it directly.
      const cmd = script && nodeBin ? nodeBin : bin;
      const args = script && nodeBin ? [script, '--version'] : ['--version'];
      const { stdout } = await execFileAsync(cmd, args, {
        timeout: 10000,
        env: { ...process.env as Record<string, string>, DSH_HOME: this.dshHome() },
      });
      return { bin, found: true, version: stdout.trim(), error: null, nodeBin };
    } catch (e) {
      return { bin, found: true, version: null, error: e instanceof Error ? e.message : String(e), nodeBin };
    }
  }

  /**
   * Detect a usable Node.js binary.
   * Order: explicit setting > PATH > common install dirs > nvm/volta.
   */
  async detectNode(): Promise<string | null> {
    const explicit = this.settings.nodeBin.trim();
    if (explicit) {
      return (await this.exists(explicit)) ? explicit : null;
    }
    // PATH lookup (usually empty under Electron, but harmless to try)
    try {
      const { stdout } = await execFileAsync('which', ['node'], { timeout: 5000 });
      const p = stdout.trim();
      if (p && (await this.exists(p))) return p;
    } catch {
      // not in PATH
    }
    for (const candidate of COMMON_NODE_CANDIDATES) {
      if (await this.exists(candidate)) return candidate;
    }
    // nvm: ~/.nvm/versions/node/vX.Y.Z/bin/node — pick the newest by semver
    // (not lexicographic, which would rank v9 above v18).
    try {
      const nvmRoot = path.join(os.homedir(), '.nvm', 'versions', 'node');
      const versions = fs.readdirSync(nvmRoot)
        .filter((v) => /^v\d+\.\d+\.\d+/.test(v))
        .sort((a, b) => versionCmp(b, a));
      for (const v of versions) {
        const p = path.join(nvmRoot, v, 'bin', 'node');
        if (await this.exists(p)) return p;
      }
    } catch {
      // no nvm
    }
    // volta
    const volta = path.join(os.homedir(), '.volta', 'bin', 'node');
    if (await this.exists(volta)) return volta;
    return null;
  }

  /**
   * Resolve the real entry script of the dsh CLI.
   * npm's global bin entries are symlinks (dsh -> ../lib/node_modules/
   * @deepseek-ai/dsh/lib/bin.js); we need the real path to run it with node.
   * Returns null when the resolved file is not node-runnable (a shell wrapper
   * or native binary), so callers can surface a clear diagnostic instead of
   * failing later with a node syntax error.
   */
  resolveDshScript(dshBin: string): string | null {
    try {
      const real = fs.realpathSync(dshBin);
      return isNodeScript(real) ? real : null;
    } catch {
      return null;
    }
  }

  /** Effective DSH_HOME (expand ~). */
  dshHome(): string {
    const home = this.settings.dshHome.trim() || '~/.dsh';
    if (home === '~/.dsh') {
      return path.join(os.homedir(), '.dsh');
    }
    return home.startsWith('~/') ? path.join(os.homedir(), home.slice(2)) : home;
  }

  /**
   * Plugin-owned DSH_HOME: an isolated directory inside the vault so the
   * per-task model / reasoning settings never pollute the user's global
   * `~/.dsh` (which the web app also reads). Credentials are symlinked from
   * the user's real DSH_HOME; settings.yaml is (re)written on every task
   * with the currently selected model + reasoning effort.
   *
   * Returns the plugin home, or null on failure (caller falls back to the
   * user home, where the model dropdown is then ignored).
   */
  ensurePluginDshHome(
    vaultRoot: string,
    sel: { model: string; effort: string },
  ): string | null {
    const base = path.join(vaultRoot, '.obsidian', 'plugins', 'dsh-obsidian', 'dsh-home');
    try {
      fs.mkdirSync(base, { recursive: true });
      // Same as ensureVaultPatch: force standard perms (missing execute bit
      // silently breaks settings.yaml writes).
      fs.chmodSync(base, 0o755);
      // Reuse credentials from the user's real DSH home (symlink once).
      const credSrc = path.join(this.dshHome(), '.credentials.yaml');
      const credDst = path.join(base, '.credentials.yaml');
      if (fs.existsSync(credSrc) && !fs.existsSync(credDst)) {
        fs.symlinkSync(credSrc, credDst);
      }
      // The deepseek provider consumes `agent-default-model` settings
      // section (provider/model) plus its reasoningEffort.
      const settings = [
        'agent-default-model:',
        '  provider: deepseek-official',
        `  model: ${sel.model}`,
        `  reasoningEffort: ${sel.effort}`,
        '',
      ].join('\n');
      fs.writeFileSync(path.join(base, 'settings.yaml'), settings, 'utf8');
      return base;
    } catch {
      return null;
    }
  }

  /**
   * Directory the agent works on. Empty = vault root.
   * Returns an absolute path; ensures it exists.
   */
  workdir(vaultRoot: string): string {
    const rel = this.settings.workdir.trim();
    if (!rel) return vaultRoot;
    // Resolve `..` and absolute paths, then verify the result stays inside the
    // vault: the workspace root is ALSO the sandbox write boundary, so an
    // out-of-vault workdir would silently move that boundary.
    const base = path.resolve(vaultRoot, rel);
    const rel2 = path.relative(vaultRoot, base);
    if (rel2 === '..' || rel2.startsWith('..' + path.sep)) {
      return vaultRoot;
    }
    try {
      fs.mkdirSync(base, { recursive: true });
    } catch {
      // read-only vault subpath: fall back to root
      return vaultRoot;
    }
    return base;
  }

  /**
   * Generate (once per vault) the persona patch overlay that turns the
   * generic coding agent into a vault-aware assistant, plus the think-relay
   * plugin patch that streams reasoning blocks to stdout.
   *
   * Returns paths to both patch files (either may be null on failure).
   */
  async ensureVaultPatch(
    vaultRoot: string,
  ): Promise<{ persona: string | null; think: string | null }> {
    const dir = path.join(vaultRoot, '.obsidian', 'plugins', 'dsh-obsidian', 'generated');
    try {
      fs.mkdirSync(dir, { recursive: true });
      // Some environments create dirs without the execute bit, which breaks
      // file creation inside; force standard perms so the plugin always works.
      fs.chmodSync(dir, 0o755);
    } catch {
      return { persona: null, think: null };
    }

    // 1) Persona patch (user-editable; never overwritten once present)
    let persona: string | null = null;
    const personaFile = path.join(dir, 'vault.yml');
    if (fs.existsSync(personaFile)) {
      persona = personaFile;
    } else {
      const personaLines = [
        '你是运行在 Obsidian vault 里的 DeepSeek Harness 助手。',
        '你的工作目录 {{cwd}} 就是用户的 vault。',
        '规则:',
        '1. 新建笔记使用 Markdown + YAML frontmatter,笔记间用 [[wikilink]] 互链。',
        '2. 需要修改 vault 内文件时直接用文件工具完成,不要只给代码。',
        '3. 删除/覆盖/移动等破坏性操作前,先向用户说明并征得同意。',
        '4. 用用户消息的语言回答。',
      ];
      if (this.settings.customPersona.trim()) {
        personaLines.push('', '附加用户指令:', this.settings.customPersona.trim());
      }
      const yaml = [
        '# 由 dsh-obsidian 生成。可自由编辑,插件不会覆盖此文件。',
        '- id: system-prompt',
        '  config:',
        '    persona: >-',
        ...personaLines.map((line) => `      ${line}`),
        '',
      ].join('\n');
      try {
        fs.writeFileSync(personaFile, yaml, 'utf8');
        persona = personaFile;
      } catch {
        persona = null;
      }
    }

    // 2) Stream-relay plugin patch (plugin-managed; regenerated on upgrade)
    let think: string | null = null;
    const thinkJs = path.join(dir, 'stream-relay.js');
    const thinkYml = path.join(dir, 'stream.yml');
    try {
      fs.writeFileSync(thinkJs, STREAM_RELAY_SRC, 'utf8');
      const yml = [
        '# 由 dsh-obsidian 生成。实时输出 agent 的思考( reasoning )与',
        '# 工具调用( tool )事件,格式 "DLEVENT\\t<json>" 供插件流式解析。',
        '- insert:',
        `    - id: dsh-obsidian-stream-relay`,
        `      name: ${JSON.stringify(thinkJs)}`,
        '',
      ].join('\n');
      fs.writeFileSync(thinkYml, yml, 'utf8');
      think = thinkYml;
    } catch {
      think = null;
    }

    return { persona, think };
  }

  /** Assemble the final task text handed to `dsh --profile headless`. */
  buildTask(userMessage: string, memory: string[], extraContext?: string): string {
    const parts: string[] = [];
    if (this.settings.memoryEnabled && memory.length > 0) {
      parts.push(memory.join('\n'));
    }
    if (extraContext && extraContext.trim()) {
      parts.push(`[上下文]\n${extraContext.trim()}`);
    }
    parts.push(userMessage);
    return parts.join('\n\n');
  }

  private async exists(p: string): Promise<boolean> {
    try {
      await fs.promises.access(p, fs.constants.X_OK);
      return true;
    } catch {
      return false;
    }
  }
}
