import { execFile } from 'child_process';
import { promisify } from 'util';
import * as os from 'os';
import * as path from 'path';
import * as fs from 'fs';
import { versionCmp } from './pure';
import type { DshDiagnostics } from './dsh-client';
import type { DshSettings } from './settings';
import { ensureObsidianSkill, MEMORY_FILE } from './obsidian-skill';

const execFileAsync = promisify(execFile);

/**
 * Command construction and environment probing for the dsh CLI.
 *
 * - Detects the `dsh` binary (explicit setting > PATH > common locations).
 * - Detects a Node.js binary and dsh's real entry script so the plugin can
 *   spawn `node <dsh>/lib/bin.js` directly. Obsidian's Electron process runs
 *   with a restricted PATH (no Homebrew/nvm dirs), so relying on the `dsh`
 *   shebang (`#!/usr/bin/env node`) fails with "env: node: No such file or
 *   directory".
 * - Warms up the `headless` profile on first use (dsh bootstraps the
 *   profile directory under DSH_HOME on demand).
 * - Generates the vault persona `--patch` overlay once per vault.
 * - Assembles the task text: conversation memory + user message.
 */

const COMMON_BIN_CANDIDATES = [
  '/opt/homebrew/bin/dsh',
  '/usr/local/bin/dsh',
  '/usr/bin/dsh',
];

const COMMON_NODE_CANDIDATES = [
  '/opt/homebrew/bin/node',
  '/usr/local/bin/node',
  '/usr/bin/node',
];

/**
 * Common install locations for the official Obsidian CLI (`obsidian`).
 * Obsidian 1.12+ registers the CLI through its installer ("Settings → General
 * → Command line interface"); on macOS it usually lands in /usr/local/bin or
 * ~/.local/bin. The plugin probes these as a fallback when it isn't on PATH.
 */
const COMMON_OBSIDIAN_CLI_CANDIDATES = [
  '/opt/homebrew/bin/obsidian',
  '/usr/local/bin/obsidian',
  '/usr/bin/obsidian',
  path.join(os.homedir(), '.local', 'bin', 'obsidian'),
];

/** Bump to force regeneration of the generated persona patch (see migration). */
const PERSONA_VERSION = 3;
const PERSONA_MARKER = `# dsh-obsidian-persona-v${PERSONA_VERSION}`;

/**
 * Source of the stream-relay DSH plugin injected via --patch.
 * It listens on the live `session/event` stream and emits real-time
 * JSON Lines (`DLEVENT\t<json>`) for reasoning blocks and tool calls:
 *   {t:'think', text}                       reasoning increment
 *   {t:'tool', status:'start', id, name, args}   tool call started
 *   {t:'tool', status:'result', id, ok, summary} tool result
 * The headless runner itself only prints the final text at the end, so
 * without this plugin the plugin never sees thinking or tool activity live.
 */
const STREAM_RELAY_SRC = `// dsh-obsidian stream relay: real-time thinking + tool events.
// Injected as a patch overlay; owned and regenerated by the plugin.
module.exports = {
  name: 'dsh-obsidian-stream-relay',
  apply(ctx) {
    const callNames = new Map();
    const emit = (obj) => process.stdout.write('DLEVENT\\t' + JSON.stringify(obj) + '\\n');
    const truncate = (s, n) => (s.length > n ? s.slice(0, n) + '…' : s);
    const summarizeArgs = (args) => {
      if (!args || typeof args !== 'object') return String(args ?? '');
      const pick = ['command', 'filePath', 'path', 'query', 'pattern', 'url', 'text', 'target', 'from', 'to'];
      const parts = [];
      for (const k of pick) if (typeof args[k] === 'string' && args[k]) parts.push(k + '=' + truncate(args[k], 60));
      return parts.length ? parts.join(' ') : truncate(JSON.stringify(args), 120);
    };
    // Tool results nest text: [{type:'tool-result', content:[{type:'text', text}]}]
    const collectText = (node, out) => {
      if (Array.isArray(node)) {
        for (const c of node) collectText(c, out);
        return;
      }
      if (typeof node === 'string') { out.push(node); return; }
      if (!node || typeof node !== 'object') return;
      if (typeof node.text === 'string') out.push(node.text);
      if (Array.isArray(node.content)) {
        for (const c of node.content) collectText(c, out);
      } else if (node.content && typeof node.content === 'object') {
        collectText(node.content, out);
      }
    };
    const summarizeResult = (content) => {
      const out = [];
      collectText(content, out);
      const text = out.join('\\n').trim();
      return text ? truncate(text, 300) : '';
    };
    ctx.on('session/event', (session, event) => {
      switch (event.type) {
        case 'assistant/message': {
          for (const b of event.data.message.content ?? []) {
            if (b.type === 'reasoning' && b.text) emit({ t: 'think', text: b.text });
          }
          break;
        }
        case 'tool/call': {
          callNames.set(event.data.callId, event.data.name);
          emit({
            t: 'tool',
            status: 'start',
            id: event.data.callId,
            name: event.data.name,
            args: summarizeArgs(event.data.arguments),
            argsFull: JSON.stringify(event.data.arguments)
          });
          break;
        }
        case 'tool/result': {
          const msg = event.data.message ?? {};
          // callId lives on message.source.callId (not on the message root)
          const callId = msg.callId ?? msg.source?.callId;
          const name = callNames.get(callId) ?? 'tool';
          emit({ t: 'tool', status: 'result', id: callId, ok: msg.isError !== true, summary: summarizeResult(msg.content) });
          break;
        }
        default:
          break;
      }
    });
  }
};
`;

/** Whether a resolved dsh entry is a JS file node can run directly. */
function isNodeScript(p: string): boolean {
  if (/\.(?:m?js|cjs)$/i.test(p)) return true;
  try {
    return /^#!.*\bnode\b/.test(fs.readFileSync(p, 'utf8').slice(0, 128));
  } catch {
    return false;
  }
}

export class DshRunner {
  constructor(private settings: DshSettings) {}

  /** Resolve the dsh binary path, or null when not found. */
  async detectBin(): Promise<string | null> {
    const explicit = this.settings.dshBin.trim();
    if (explicit) {
      if (await this.exists(explicit)) return explicit;
      return null;
    }
    // PATH lookup
    try {
      const { stdout } = await execFileAsync('which', ['dsh'], { timeout: 5000 });
      const p = stdout.trim();
      if (p) return p;
    } catch {
      // not in PATH
    }
    for (const candidate of COMMON_BIN_CANDIDATES) {
      if (await this.exists(candidate)) return candidate;
    }
    return null;
  }

  /** Probe binary + profile readiness for the settings page. */
  async diagnose(): Promise<DshDiagnostics> {
    const bin = await this.detectBin();
    const nodeBin = await this.detectNode();
    if (!bin) {
      return { bin: '', found: false, version: null, error: 'not-found', nodeBin };
    }
    try {
      const script = this.resolveDshScript(bin);
      // Prefer `node <script> --version` (bypasses the shebang under Electron's
      // restricted PATH); when the bin isn't node-runnable, invoke it directly.
      const cmd = script && nodeBin ? nodeBin : bin;
      const args = script && nodeBin ? [script, '--version'] : ['--version'];
      const { stdout } = await execFileAsync(cmd, args, {
        timeout: 10000,
        env: { ...process.env as Record<string, string>, DSH_HOME: this.dshHome() },
      });
      return { bin, found: true, version: stdout.trim(), error: null, nodeBin };
    } catch (e) {
      return { bin, found: true, version: null, error: e instanceof Error ? e.message : String(e), nodeBin };
    }
  }

  /**
   * Detect a usable Node.js binary.
   * Order: explicit setting > PATH > common install dirs > nvm/volta.
   */
  async detectNode(): Promise<string | null> {
    const explicit = this.settings.nodeBin.trim();
    if (explicit) {
      return (await this.exists(explicit)) ? explicit : null;
    }
    // PATH lookup (usually empty under Electron, but harmless to try)
    try {
      const { stdout } = await execFileAsync('which', ['node'], { timeout: 5000 });
      const p = stdout.trim();
      if (p && (await this.exists(p))) return p;
    } catch {
      // not in PATH
    }
    for (const candidate of COMMON_NODE_CANDIDATES) {
      if (await this.exists(candidate)) return candidate;
    }
    // nvm: ~/.nvm/versions/node/vX.Y.Z/bin/node — pick the newest by semver
    // (not lexicographic, which would rank v9 above v18).
    try {
      const nvmRoot = path.join(os.homedir(), '.nvm', 'versions', 'node');
      const versions = fs.readdirSync(nvmRoot)
        .filter((v) => /^v\d+\.\d+\.\d+/.test(v))
        .sort((a, b) => versionCmp(b, a));
      for (const v of versions) {
        const p = path.join(nvmRoot, v, 'bin', 'node');
        if (await this.exists(p)) return p;
      }
    } catch {
      // no nvm
    }
    // volta
    const volta = path.join(os.homedir(), '.volta', 'bin', 'node');
    if (await this.exists(volta)) return volta;
    return null;
  }

  /**
   * Resolve the real entry script of the dsh CLI.
   * npm's global bin entries are symlinks (dsh -> ../lib/node_modules/
   * @deepseek-ai/dsh/lib/bin.js); we need the real path to run it with node.
   * Returns null when the resolved file is not node-runnable (a shell wrapper
   * or native binary), so callers can surface a clear diagnostic instead of
   * failing later with a node syntax error.
   */
  resolveDshScript(dshBin: string): string | null {
    try {
      const real = fs.realpathSync(dshBin);
      return isNodeScript(real) ? real : null;
    } catch {
      return null;
    }
  }

  /** Effective DSH_HOME (expand ~). */
  dshHome(): string {
    const home = this.settings.dshHome.trim() || '~/.dsh';
    if (home === '~/.dsh') {
      return path.join(os.homedir(), '.dsh');
    }
    return home.startsWith('~/') ? path.join(os.homedir(), home.slice(2)) : home;
  }

  /**
   * Plugin-owned DSH_HOME: an isolated directory inside the vault so the
   * per-task model / reasoning settings never pollute the user's global
   * `~/.dsh` (which the web app also reads). Credentials are symlinked from
   * the user's real DSH_HOME; settings.yaml is (re)written on every task
   * with the currently selected model + reasoning effort.
   *
   * Returns the plugin home, or null on failure (caller falls back to the
   * user home, where the model dropdown is then ignored).
   */
  /** Absolute path of the plugin-owned DSH_HOME inside the vault. */
  pluginHomeDir(vaultRoot: string): string {
    return path.join(vaultRoot, '.obsidian', 'plugins', 'dsh-obsidian', 'dsh-home');
  }

  ensurePluginDshHome(
    vaultRoot: string,
    sel: { model: string; effort: string },
  ): string | null {
    const base = this.pluginHomeDir(vaultRoot);
    try {
      fs.mkdirSync(base, { recursive: true });
      // Same as ensureVaultPatch: force standard perms (missing execute bit
      // silently breaks settings.yaml writes).
      fs.chmodSync(base, 0o755);
      // Reuse credentials from the user's real DSH home (symlink once).
      const credSrc = path.join(this.dshHome(), '.credentials.yaml');
      const credDst = path.join(base, '.credentials.yaml');
      if (fs.existsSync(credSrc) && !fs.existsSync(credDst)) {
        fs.symlinkSync(credSrc, credDst);
      }
      // The deepseek provider consumes `agent-default-model` settings
      // section (provider/model) plus its reasoningEffort.
      const settings = [
        'agent-default-model:',
        '  provider: deepseek-official',
        `  model: ${sel.model}`,
        `  reasoningEffort: ${sel.effort}`,
        '',
      ].join('\n');
      fs.writeFileSync(path.join(base, 'settings.yaml'), settings, 'utf8');
      return base;
    } catch {
      return null;
    }
  }

  /**
   * Directory the agent works on. Empty = vault root.
   * Returns an absolute path; ensures it exists.
   */
  workdir(vaultRoot: string): string {
    const rel = this.settings.workdir.trim();
    if (!rel) return vaultRoot;
    // Resolve `..` and absolute paths, then verify the result stays inside the
    // vault: the workspace root is ALSO the sandbox write boundary, so an
    // out-of-vault workdir would silently move that boundary.
    const base = path.resolve(vaultRoot, rel);
    const rel2 = path.relative(vaultRoot, base);
    if (rel2 === '..' || rel2.startsWith('..' + path.sep)) {
      return vaultRoot;
    }
    try {
      fs.mkdirSync(base, { recursive: true });
    } catch {
      // read-only vault subpath: fall back to root
      return vaultRoot;
    }
    return base;
  }

  /**
   * Write the built-in `obsidian` skill into the plugin-owned DSH_HOME so the
   * headless agent discovers it via dsh-skill-filesystem (<dshHome>/skills,
   * rank 400). Plugin-owned: always regenerated so the skill tracks the plugin
   * version. Users override it by dropping their own skill at
   * `<vault>/.dsh/skills/obsidian/` (rank 100 project root, wins).
   *
   * Returns the skill directory, or null on failure / when disabled.
   */
  ensureObsidianSkill(vaultRoot: string): string | null {
    if (!this.settings.obsidianSkill) return null;
    const skillRoot = path.join(this.pluginHomeDir(vaultRoot), 'skills');
    try {
      fs.mkdirSync(skillRoot, { recursive: true });
      fs.chmodSync(skillRoot, 0o755);
    } catch {
      return null;
    }
    const res = ensureObsidianSkill(skillRoot);
    return res ? res.dir : null;
  }

  /**
   * Seed the long-term memory file at the vault root (Harness/memory.md) so
   * the agent always finds it. The official CLI addresses it vault-relative
   * (`obsidian read/append path="Harness/memory.md"`), which keeps it
   * reachable even when the sandbox workdir is a vault subfolder.
   */
  ensureMemoryFile(vaultRoot: string): string | null {
    const file = path.join(vaultRoot, MEMORY_FILE);
    try {
      if (!fs.existsSync(file)) {
        fs.mkdirSync(path.dirname(file), { recursive: true });
        const seed = [
          '# 长期记忆 (Long-term memory)',
          '',
          '> 由 DeepHarness 维护。agent 在每次任务开始时读这里、结束时把跨会话结论写回这里。',
          '> 你可以自由编辑;删除某行即让 agent 忘记那条结论。',
          '',
          '## Vault 结构',
          '',
          '## 用户偏好',
          '',
          '## 进行中的项目',
          '',
        ].join('\n');
        fs.writeFileSync(file, seed, 'utf8');
      }
      return file;
    } catch {
      return null;
    }
  }

  /**
   * Generate the skill-dirs patch that registers user-configured extra skill
   * directories (settings.extraSkillDirs, e.g. Library/Skills or .claude/skills)
   * with dsh-skill-filesystem's `customSkillDirs`, so `/name` invocation sees
   * them. Regenerated on every run, like the stream-relay patch.
   *
   * Returns the patch path, or null when there is nothing to register.
   */
  ensureSkillDirsPatch(vaultRoot: string): string | null {
    const dirs: string[] = [];
    for (const rel of this.settings.extraSkillDirs.split(',')) {
      const t = rel.trim();
      if (!t) continue;
      const abs = path.resolve(vaultRoot, t);
      try {
        if (fs.statSync(abs).isDirectory()) dirs.push(abs);
      } catch {
        // missing dir: skip (valid empty state)
      }
    }
    if (dirs.length === 0) return null;
    const dir = path.join(vaultRoot, '.obsidian', 'plugins', 'dsh-obsidian', 'generated');
    const file = path.join(dir, 'skill-dirs.yml');
    try {
      fs.mkdirSync(dir, { recursive: true });
      fs.chmodSync(dir, 0o755);
      const yml = [
        '# 由 dsh-obsidian 生成。把附加技能目录注册给 DSH 的 skill-filesystem',
        '# (customSkillDirs),使 /技能名 斜杠调用能发现这些目录里的 skill。',
        '- id: skill-filesystem',
        '  config:',
        '    customSkillDirs:',
        ...dirs.map((d) => `      - ${JSON.stringify(d)}`),
        '',
      ].join('\n');
      fs.writeFileSync(file, yml, 'utf8');
      return file;
    } catch {
      return null;
    }
  }

  /** Resolve the official Obsidian CLI path (explicit setting or null). */
  obsidianCliBin(): string | null {
    const explicit = this.settings.obsidianCli.trim();
    return explicit ? explicit : null;
  }

  /**
   * Detect the official Obsidian CLI (`obsidian`). Order: explicit setting >
   * PATH > common install locations. Returns the binary path, or null when
   * unavailable (Obsidian <1.12, or the CLI not enabled/registered in
   * Obsidian's Settings → General → Command line interface).
   */
  async detectObsidianCli(): Promise<string | null> {
    const explicit = this.obsidianCliBin();
    if (explicit && (await this.exists(explicit))) return explicit;
    try {
      const { stdout } = await execFileAsync('which', ['obsidian'], { timeout: 5000 });
      const p = stdout.trim();
      if (p && (await this.exists(p))) return p;
    } catch {
      // not in PATH
    }
    for (const candidate of COMMON_OBSIDIAN_CLI_CANDIDATES) {
      if (await this.exists(candidate)) return candidate;
    }
    return null;
  }

  /**
   * Generate (once per vault) the persona patch overlay that turns the
   * generic coding agent into a vault-aware assistant, plus the think-relay
   * plugin patch that streams reasoning blocks to stdout.
   *
   * Returns paths to both patch files (either may be null on failure).
   */
  async ensureVaultPatch(
    vaultRoot: string,
  ): Promise<{ persona: string | null; think: string | null }> {
    const dir = path.join(vaultRoot, '.obsidian', 'plugins', 'dsh-obsidian', 'generated');
    try {
      fs.mkdirSync(dir, { recursive: true });
      // Some environments create dirs without the execute bit, which breaks
      // file creation inside; force standard perms so the plugin always works.
      fs.chmodSync(dir, 0o755);
    } catch {
      return { persona: null, think: null };
    }

    // 1) Persona patch (user-editable; regenerated only on a version bump)
    let persona: string | null = null;
    const personaFile = path.join(dir, 'vault.yml');
    try {
      if (!fs.existsSync(personaFile)) {
        fs.writeFileSync(personaFile, this.renderPersonaYaml(this.buildPersonaLines(), PERSONA_MARKER), 'utf8');
      } else {
        const existing = fs.readFileSync(personaFile, 'utf8');
        if (!existing.includes(PERSONA_MARKER)) {
          // Pre-v2 generated file. Preserve any user edits as a .bak, then
          // regenerate with the current default + custom persona.
          const legacy = this.renderLegacyPersonaYaml();
          if (existing.trim() !== legacy.trim()) {
            try { fs.writeFileSync(`${personaFile}.bak`, existing, 'utf8'); } catch { /* ignore */ }
          }
          fs.writeFileSync(personaFile, this.renderPersonaYaml(this.buildPersonaLines(), PERSONA_MARKER), 'utf8');
        }
      }
      persona = personaFile;
    } catch {
      persona = null;
    }

    // 2) Stream-relay plugin patch (plugin-managed; regenerated on upgrade)
    let think: string | null = null;
    const thinkJs = path.join(dir, 'stream-relay.js');
    const thinkYml = path.join(dir, 'stream.yml');
    try {
      fs.writeFileSync(thinkJs, STREAM_RELAY_SRC, 'utf8');
      const yml = [
        '# 由 dsh-obsidian 生成。实时输出 agent 的思考( reasoning )与',
        '# 工具调用( tool )事件,格式 "DLEVENT\\t<json>" 供插件流式解析。',
        '- insert:',
        `    - id: dsh-obsidian-stream-relay`,
        `      name: ${JSON.stringify(thinkJs)}`,
        '',
      ].join('\n');
      fs.writeFileSync(thinkYml, yml, 'utf8');
      think = thinkYml;
    } catch {
      think = null;
    }

    return { persona, think };
  }

  /** Default persona body (v3): Claudian-style Obsidian expert + L1 rules. */
  private buildPersonaLines(): string[] {
    const lines = [
      '你是 Claudian 风格的 Obsidian 专家助手,专精 vault 管理、知识组织与代码分析,直接在用户的 Obsidian vault 内工作。',
      '你的工作目录 {{cwd}} 就是 vault(或其子目录)。',
      '价值观:安全第一(不理解上下文绝不覆盖数据)、主动思考(先计划后验证,主动预判断链/缺失文件)、精准克制(改动精确、最小噪音)。',
      '路径规则:vault 内文件一律用相对 vault 根的相对路径(前导 / 或绝对路径会失败);写 vault 外的文件必须先征得同意并切换到「完全访问」。',
      '工具规范:编辑任何文件前先读它;edit 的 old_string 必须与文件内容逐字符一致,失败就重读核对;文件操作用文件工具,bash 只用于文件工具做不到的事;两步及以上的任务用 todo 列表追踪进度。',
      '安全工作流:上下文(信息够不够)→ 影响(会不会断链/影响其他文件)→ 计划(多步列 todo)→ 执行(最小改动)→ 验证(frontmatter、Dataview、链接是否完好)。',
      '回复规范:提到 vault 里的文件时用 [[wikilink]](可点击),展示图片用 ![[图片.png]] 嵌入,不要用裸路径。',
      'Obsidian 语法:Markdown + YAML frontmatter(尊重并保留已有字段)、[[wikilink]]、#tag、![[嵌入]]、> [!note] callout;```dataview 查询块视为只读,不要破坏。',
      '涉及笔记/frontmatter/wikilink/标签/日记/反链/模板等 vault 操作时,先用 skill 工具加载 obsidian 技能,再按其中的约定与命令执行。',
      '优先使用官方 obsidian CLI(若可用)做 vault 级操作(读、搜索、frontmatter、标签、日记、反链);CLI 不可用时降级为文件工具。',
      '长期记忆:任务开始时先读 vault 根目录的 Harness/memory.md 带回上次结论;产生需要跨会话记住的结论(vault 结构、用户偏好、进行中的项目)时写回该文件。',
      'obsidian CLI 不受 DSH 文件沙箱约束:obsidian eval 仅用于只读查询;删除/移动/覆盖仍需先征得同意。',
    ];
    if (this.settings.customPersona.trim()) {
      lines.push('', '附加用户指令:', this.settings.customPersona.trim());
    }
    return lines;
  }

  private renderPersonaYaml(lines: string[], marker: string): string {
    return [
      marker,
      '# 由 dsh-obsidian 生成。可自由编辑;插件升级时可能重新生成(旧版会备份为 vault.yml.bak)。',
      '- id: system-prompt',
      '  config:',
      '    persona: >-',
      ...lines.map((line) => `      ${line}`),
      '',
    ].join('\n');
  }

  /** Reconstruct the pre-v2 default for migration comparison. */
  private renderLegacyPersonaYaml(): string {
    const lines = [
      '你是运行在 Obsidian vault 里的 DeepSeek Harness 助手。',
      '你的工作目录 {{cwd}} 就是用户的 vault。',
      '规则:',
      '1. 新建笔记使用 Markdown + YAML frontmatter,笔记间用 [[wikilink]] 互链。',
      '2. 需要修改 vault 内文件时直接用文件工具完成,不要只给代码。',
      '3. 删除/覆盖/移动等破坏性操作前,先向用户说明并征得同意。',
      '4. 用用户消息的语言回答。',
    ];
    if (this.settings.customPersona.trim()) {
      lines.push('', '附加用户指令:', this.settings.customPersona.trim());
    }
    return [
      '# 由 dsh-obsidian 生成。可自由编辑,插件不会覆盖此文件。',
      '- id: system-prompt',
      '  config:',
      '    persona: >-',
      ...lines.map((line) => `      ${line}`),
      '',
    ].join('\n');
  }

  /** Assemble the final task text handed to `dsh --profile headless`. */
  buildTask(userMessage: string, memory: string[], extraContext?: string): string {
    const parts: string[] = [];
    if (this.settings.memoryEnabled && memory.length > 0) {
      parts.push(memory.join('\n'));
    }
    if (extraContext && extraContext.trim()) {
      parts.push(`[上下文]\n${extraContext.trim()}`);
    }
    parts.push(userMessage);
    return parts.join('\n\n');
  }

  private async exists(p: string): Promise<boolean> {
    try {
      await fs.promises.access(p, fs.constants.X_OK);
      return true;
    } catch {
      return false;
    }
  }
}
